export const foodItems = [
    {id:1,title: "Grilled chicken breast (3 oz)", calories:140,source: require('./assets/grilledchicken.jpg')}, 
    {id:2,title: "Quinoa(1/2 cup cooked )", calories:111,source: require('./assets/quinoa.jpg')},
    {id:3,title: "Broccoli (1 cup chopped)", calories:55,source: require('./assets/broccoli.webp')},
    {id:4,title: "Greek Yogurt (6 oz)", calories:100,source: require('./assets/greekyogurt.jpg')},
    {id:5,title: "Sweet Potato (1 medium)", calories:103,source: require('./assets/sweetpotato.jpg')},
    {id:6,title: "Salmon (3 oz)", calories:155,source: require('./assets/salmon.jpg')},
    {id:7,title: "Brown Rice(1/2 cup cooked)", calories:140,source: require('./assets/brownrice.webp')},
    {id:8,title: "Spinach (1 cup raw)", calories:7,source: require('./assets/spinach.jpg')},
    {id:9,title: "Almonds(1 oz)", calories:163,source: require('./assets/almonds.jpg')},
    {id:10,title: "Blueberries(1 cup)", calories:84,source: require('./assets/blueberries.jpg')},
  
    {id:11,title: "Banana(1)", calories:105,source: require('./assets/bananas.png')},
    {id:12,title: "apple(1)", calories:95,source: require('./assets/apple.jpg')},
    {id:13,title: "Potato(1)", calories:110,source: require('./assets/potatos.jpg')},
    {id:14,title: "broccoli(1)", calories:50,source: require('./assets/broccoli.jpg')},
    {id:15,title: "fried Chiken(1)", calories:83,source: require('./assets/friedChicken.jpg')},
    {id:16,title: "brown rice(1 package)", calories:216,source: require('./assets/brownRice.jpg')},
    {id:17,title: "Orange(1)", calories:45,source: require('./assets/orange.jpg')},
    {id:18,title: "peanuts(1 cup)", calories:828,source: require('./assets/peanuts.jpg')},
    {id:19,title: "pancakes(1)", calories:84,source: require('./assets/pancakes.jpg')},
    {id:20,title: "waffles(1)", calories:82,source: require('./assets/waffle.png')},
  ]